print(10)
print("Hola Mundo!")
print(True)
print(False)
print(1.01)
print(1+2)
print(1+2)
print(1+2)
print(1+2)
print(1+2)
print("ejemplo operaciones aritmeticas")
print("El resultado de la suma 37+12 es ", 37+12)
print("El resultado de la resta 47-17 es ", 47-17)
print("El resultado de la multiplicacion 6*7 es ", 6*7)
print("El resultado de la division 50/5 es ", 50/5)
print('Esta es otra forma de escribir valores {}+{} es {}'.format(1,2,1+2))

